export type Question = { prompt: string; options: [string, string, string, string] };
export type QuestionPack = "mixed" | "everyday" | "chaos" | "close";

export const QUESTIONS: Question[] = [
  { prompt: "A surprise free flight appears. Where do you go?", options: ["Tropical island", "Huge city", "The mountains", "Wherever food is best"] },
  { prompt: "Which useless superpower would you actually want?", options: ["Always find parking", "Perfect toast every time", "Never need to queue", "Talk to houseplants"] },
  { prompt: "Your ideal Friday night is…", options: ["Big night out", "Movie and snacks", "Dinner with friends", "Deep in a hobby"] },
  { prompt: "Pick one thing to bring to a deserted island.", options: ["A satellite phone", "A brilliant chef", "An endless book", "A luxury tent"] },
  { prompt: "What would you be famous for?", options: ["A wild invention", "A viral accident", "A bestselling book", "Winning a game show"] },
  { prompt: "Choose your road-trip role.", options: ["Driver", "DJ", "Snack captain", "Route planner"] },
  { prompt: "Which weather matches your personality?", options: ["Bright sunshine", "Dramatic thunder", "Cozy rain", "Crisp snow"] },
  { prompt: "A time machine gets one trip. Where are you going?", options: ["Ancient world", "My childhood", "100 years ahead", "Last weekend"] },
  { prompt: "Which tiny inconvenience is the worst?", options: ["Wet socks", "Slow Wi-Fi", "A tangled cable", "Missing the lift"] },
  { prompt: "Pick a dream home feature.", options: ["Secret library", "Rooftop pool", "Cinema room", "Huge garden"] },
  { prompt: "What is your group-chat energy?", options: ["Meme supplier", "Silent observer", "Plan organizer", "Voice-note novelist"] },
  { prompt: "Choose a snack that disappears first.", options: ["Chips", "Chocolate", "Fruit", "Cheese"] },
  { prompt: "What would you do with an unexpected day off?", options: ["Sleep", "Go somewhere", "Finish a project", "Call friends"] },
  { prompt: "Pick a reality show to survive.", options: ["Cooking contest", "Island survival", "Talent show", "Trivia championship"] },
  { prompt: "Which pet would you trust with a secret?", options: ["Dog", "Cat", "Parrot", "Goldfish"] },
  { prompt: "Your phone battery is at 2%. What gets priority?", options: ["Call someone", "Order a ride", "Send one message", "Take one last photo"] },
  { prompt: "What kind of museum would you visit first?", options: ["Natural history", "Modern art", "Science", "Very strange objects"] },
  { prompt: "Choose a one-year life upgrade.", options: ["Personal chef", "Private driver", "Daily cleaner", "Personal trainer"] },
  { prompt: "Which fictional world gets your passport stamp?", options: ["Magic kingdom", "Space civilization", "Superhero city", "Cozy fantasy village"] },
  { prompt: "You must enter a competition tomorrow. Pick one.", options: ["Karaoke", "Bake-off", "Dance battle", "Speed puzzle"] },
  { prompt: "Which sound is most satisfying?", options: ["Ocean waves", "Crackling fire", "Heavy rain", "A crowd cheering"] },
  { prompt: "What is the best breakfast category?", options: ["Sweet", "Savory", "Just coffee", "Breakfast is optional"] },
  { prompt: "Pick a job for one day.", options: ["Film director", "Wildlife keeper", "Astronaut", "Theme-park tester"] },
  { prompt: "Which button would you press?", options: ["Pause time", "Undo one mistake", "Know any answer", "Instantly travel home"] },
  { prompt: "Your perfect party has…", options: ["A packed dance floor", "Board games", "A great dinner", "A tiny guest list"] },
  { prompt: "Which skill would you download instantly?", options: ["Play any instrument", "Speak every language", "Cook anything", "Fix anything"] },
  { prompt: "Pick a midnight snack.", options: ["Leftover pizza", "Cereal", "Ice cream", "Something spicy"] },
  { prompt: "What would you name a boat?", options: ["A clever pun", "A person’s name", "Something majestic", "Boat McBoatface"] },
  { prompt: "Choose your movie genre.", options: ["Comedy", "Thriller", "Sci-fi", "Drama"] },
  { prompt: "What is your holiday planning style?", options: ["Spreadsheet ready", "One rough plan", "Ask a local", "Decide after landing"] },
  { prompt: "Pick a seat on a long journey.", options: ["Window", "Aisle", "Near the front", "Anywhere quiet"] },
  { prompt: "Which everyday object would make the best mascot?", options: ["Spoon", "Sock", "Lamp", "Backpack"] },
  { prompt: "Your café order says what about you?", options: ["Keep it simple", "Make it fancy", "Make it strong", "Surprise me"] },
  { prompt: "Choose a harmless rule to break.", options: ["Dessert first", "Pajamas all day", "Sing in a library", "Breakfast at midnight"] },
  { prompt: "What wins your attention fastest?", options: ["A mystery", "A competition", "A beautiful view", "A funny story"] },
  { prompt: "Pick a theme-park ride.", options: ["Huge roller coaster", "Ferris wheel", "Water ride", "Haunted house"] },
  { prompt: "Which room do you improve first?", options: ["Kitchen", "Bedroom", "Living room", "Balcony or garden"] },
  { prompt: "Choose a color for your team uniform.", options: ["Electric blue", "Neon green", "Deep red", "All black"] },
  { prompt: "What belongs on every good playlist?", options: ["A classic", "A dance track", "A sad song", "A surprise"] },
  { prompt: "Which compliment lands best?", options: ["You’re hilarious", "You’re thoughtful", "You’re talented", "You have great taste"] },
  { prompt: "Pick a lucky charm.", options: ["A coin", "A bracelet", "A tiny toy", "I don’t need one"] },
  { prompt: "What do you photograph most?", options: ["People", "Food", "Places", "Random funny things"] },
  { prompt: "Choose a free lifetime supply.", options: ["Coffee or tea", "Shoes", "Books", "Concert tickets"] },
  { prompt: "Which school subject deserved more love?", options: ["Art", "Science", "History", "Sports"] },
  { prompt: "Pick the best smell.", options: ["Fresh bread", "Rain on pavement", "Coffee", "Clean laundry"] },
  { prompt: "How do you handle a difficult puzzle?", options: ["Keep grinding", "Look for a hint", "Ask someone", "Leave and return later"] },
  { prompt: "Choose a dramatic entrance.", options: ["Through smoke", "On a motorbike", "With theme music", "I sneak in quietly"] },
  { prompt: "What is the superior potato form?", options: ["Fries", "Mashed", "Roasted", "Chips"] },
  { prompt: "Pick a spontaneous adventure.", options: ["Night drive", "New restaurant", "Last-minute concert", "Sunrise hike"] },
  { prompt: "Which message gets the fastest reply?", options: ["Are you free?", "I have gossip", "Want food?", "Emergency meme"] },
  { prompt: "You find a hidden door. What do you hope is behind it?", options: ["Treasure", "Another world", "A secret club", "A peaceful room"] },
  { prompt: "Choose a personal robot’s main job.", options: ["Clean everything", "Cook meals", "Run errands", "Give advice"] },
  { prompt: "What makes a hotel instantly better?", options: ["Amazing breakfast", "Huge bed", "Great view", "Perfect location"] },
  { prompt: "Pick a low-stakes hill to die on.", options: ["Pineapple on pizza", "Morning showers", "How to load a dishwasher", "The correct room temperature"] },
  { prompt: "Which app would be hardest to lose for a week?", options: ["Messages", "Maps", "Music", "Video"] },
  { prompt: "Your victory celebration is…", options: ["A loud cheer", "A tiny dance", "A smug nod", "Act like it was easy"] },
  { prompt: "Choose a cabin companion.", options: ["A comedian", "A chef", "A musician", "A survival expert"] },
  { prompt: "Which shop is most dangerous for your wallet?", options: ["Bookshop", "Tech store", "Clothing store", "Grocery store while hungry"] },
  { prompt: "Pick a new annual holiday.", options: ["National Nap Day", "Second Birthday", "No-Email Day", "Free Dessert Day"] },
  { prompt: "What is your instinct in an escape room?", options: ["Search everywhere", "Solve the riddles", "Direct the team", "Try every code"] },
];

export const QUESTION_PACKS: Record<QuestionPack, number[]> = {
  mixed: QUESTIONS.map((_, index) => index),
  everyday: QUESTIONS.map((_, index) => index).slice(0, 20),
  chaos: QUESTIONS.map((_, index) => index).slice(20, 40),
  close: QUESTIONS.map((_, index) => index).slice(40, 60),
};
